# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        args: ["--dot", "--fix", "--disable", "MD013", "MD040", "--"]

  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: make fmt-go
        language: system
        pass_filenames: false
      - id: golangci-lint
        name: golangci-lint
        entry: make lint-go
        language: system
        pass_filenames: false

  - repo: https://github.com/biomejs/pre-commit
    rev: v2.4.15
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@2.4.15"]
        args: ["--config-path=biome.json"]
        files: ^web/
