// Package models exposes a static metadata catalog (context window, output
// limit, capability bits) for known model IDs. Regenerated by
// scripts/update_models_catalog.py and embedded at build time.
package models

import (
	"encoding/json"
	"strings"
	"sync"

	_ "embed"
)

//go:embed models_catalog.json
var catalogJSON []byte

// Metadata is the normalized model capability record.
type Metadata struct {
	Provider           string `json:"provider"`
	Model              string `json:"model"`
	ContextWindow      int    `json:"context_window"`
	MaxOutputTokens    int    `json:"max_output_tokens"`
	SupportsReasoning  *bool  `json:"supports_reasoning,omitempty"`
	SupportsImageInput *bool  `json:"supports_image_input,omitempty"`
	SupportsPDFInput   *bool  `json:"supports_pdf_input,omitempty"`
}

type rawMetadata struct {
	ContextWindow      int   `json:"context_window"`
	MaxOutputTokens    int   `json:"max_output_tokens"`
	SupportsReasoning  *bool `json:"supports_reasoning"`
	SupportsImageInput *bool `json:"supports_image_input"`
	SupportsPDFInput   *bool `json:"supports_pdf_input"`
}

var loadCatalog = newCatalogLoader()

func newCatalogLoader() func() map[string]map[string]rawMetadata {
	return sync.OnceValue(func() map[string]map[string]rawMetadata {
		var parsed map[string]map[string]rawMetadata
		if err := json.Unmarshal(catalogJSON, &parsed); err != nil {
			return map[string]map[string]rawMetadata{}
		}
		return parsed
	})
}

// Lookup resolves metadata for a (provider, model) pair. Tries the exact
// pair, then "<prefix>/<name>" stripped, then an unambiguous suffix match
// inside the openrouter map.
func Lookup(providerType, model string) *Metadata {
	providerType = strings.TrimSpace(providerType)
	requestedModel := strings.TrimSpace(model)
	if providerType == "" || requestedModel == "" {
		return nil
	}
	catalog := loadCatalog()
	if len(catalog) == 0 {
		return nil
	}

	modelName := requestedModel
	if _, after, ok := strings.Cut(requestedModel, "/"); ok {
		modelName = strings.TrimSpace(after)
	}

	build := func(entry rawMetadata) *Metadata {
		return &Metadata{
			Provider:           providerType,
			Model:              requestedModel,
			ContextWindow:      entry.ContextWindow,
			MaxOutputTokens:    entry.MaxOutputTokens,
			SupportsReasoning:  entry.SupportsReasoning,
			SupportsImageInput: entry.SupportsImageInput,
			SupportsPDFInput:   entry.SupportsPDFInput,
		}
	}

	if entry, ok := catalog[providerType][requestedModel]; ok {
		return build(entry)
	}
	if fallback := defaultProvider(modelName); fallback != "" && fallback != providerType {
		if entry, ok := catalog[fallback][modelName]; ok {
			return build(entry)
		}
	}

	var match rawMetadata
	found := false
	for modelID, entry := range catalog["openrouter"] {
		_, suffix, ok := strings.Cut(modelID, "/")
		if !ok || strings.TrimSpace(suffix) != modelName {
			continue
		}
		if found {
			// Ambiguous suffix match — don't guess.
			return nil
		}
		match = entry
		found = true
	}
	if found {
		return build(match)
	}
	return nil
}

// defaultProvider guesses the owning provider from a bare model name.
func defaultProvider(model string) string {
	switch m := strings.ToLower(model); {
	case strings.HasPrefix(m, "claude-"):
		return "anthropic"
	case strings.HasPrefix(m, "deepseek-"):
		return "deepseek"
	case strings.HasPrefix(m, "gemini-"):
		return "google"
	case strings.HasPrefix(m, "glm-"):
		return "zai"
	case strings.HasPrefix(m, "kimi-"):
		return "moonshotai"
	case strings.HasPrefix(m, "minimax-"):
		return "minimax"
	case strings.HasPrefix(m, "gpt-"),
		strings.HasPrefix(m, "o1"),
		strings.HasPrefix(m, "o3"),
		strings.HasPrefix(m, "o4"):
		return "openai"
	default:
		return ""
	}
}
